# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        square:
            quality: 75
            filters:
                thumbnail:
                    size: [300, 300] 
                    mode: outbond
        megasquare:
            quality: 75
            filters:
                thumbnail:
                    size: [700, 1500] 
                    mode: outbond 
        banniere:
            quality: 75
            filters:
                thumbnail:
                    size: [200, 100] 
                    mode: outbond 
        
                    